# ----------------------- #
#      Main Configs       #
# ----------------------- #
title: "@Lenciel"
email: "lenciel@gmail.com"
description: "Thoughts and Rants by Lenciel"
baseurl: ""
author: "Lenciel"
url: "https://lenciel.com"
date_format: "%Y/%m/%d %H:%M"
subscribe_rss: /feed.xml
default_asides: []
sidebar: collapse

theme: jekyll-lenciel-theme
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
permalink: /:year/:month/:title/
encoding: utf-8

# plugins
plugins_dir: ./plugins
safe: false
#include_code.rb
code_dir: downloads/code
# category_generator
category_dir: categories

highlighter: rouge
paginate: 2          # Posts per page on the blog index
paginate_path: "posts/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: true       # Converts page and post titles to titlecase

# jekyll-picture-tag
picture:
  output: "../resized"
  cdn_url: "https://cdn.lenciel.com"
  cdn_environments: ['production']
  suppress_warnings: true

# Google Analytics
google_analytics_tracking_id: UA-175991-6

# Facebook Like
facebook_like: false

# Beian
beian: 沪ICP备19012437号
